/**
 * kitBuilder.js — assemble a downloadable "deployment kit"
 * ----------------------------------------------------------------------------
 * Bundles the user's token register into a single ZIP: a human-readable
 * deployment guide, the machine-readable register, per-token snippets, decoy
 * files, QR SVGs and freshly generated PDFs.
 *
 * `fflate` is resolved through the import map in the browser and node_modules
 * under test, so this module is fully unit-testable (see tests/kitBuilder.test.js).
 */

import { zipSync, strToU8 } from "fflate";
import { TOKEN_TYPES, buildSnippets } from "./tokenEngine.js";
import { generatePdf } from "./pdfGenerator.js";

/** @typedef {import("./store.js").CanaryToken} CanaryToken */

/**
 * Build the deployment guide that ships inside the archive.
 * @param {Array<{ id: string, type: string, label: string, mode: string }>} tokens
 * @param {{ generatedAt?: string }} [options]
 * @returns {string}
 */
export function buildGuide(tokens, { generatedAt = new Date().toISOString() } = {}) {
  const rows = tokens
    .map((token) => {
      const name = TOKEN_TYPES[token.type]?.name ?? token.type;
      return `| ${safecell(token.label)} | ${name} | \`${token.id}\` | ${token.mode} |`;
    })
    .join("\n");

  return `# Canary Deployment Kit

Generated by Canary Token Generator on ${generatedAt}

This archive contains everything needed to deploy the canary tokens listed
below. **Deploy only on systems you own or are authorized to monitor.**

## Token register

| Label | Type | Canary ID | Mode |
| ----- | ---- | --------- | ---- |
${rows || "| _(no tokens)_ | | | |"}

## Contents

- \`tokens.json\` — full register, re-importable into the web app.
- \`snippets/\` — ready-to-paste HTML / Markdown / cURL for tracking links.
- \`files/\` — decoy \`.env\`, credentials and SSH config files.
- \`qr/\` — SVG QR codes for the QR canary tokens.
- \`documents/\` — generated decoy PDFs.

## How to deploy

1. Place each decoy where an intruder would be tempted to look — shared drives,
   repos, CI variables, signature blocks or physical assets.
2. Confirm your webhook endpoint is receiving beacons (use "Send test beacon"
   in the app, or \`curl\` the tracking URL).
3. When a beacon fires, match its \`ct\` (canary id) against the register above.

## Security notice

Canary tokens are a detection control and complement, never replace, access
control and logging. Use them responsibly and within the law.
`;
}

function safecell(value) {
  return String(value ?? "").replace(/\|/g, "\\|");
}

/**
 * Build the ZIP archive.
 *
 * @param {CanaryToken[]} tokens
 * @param {object} [payload]                 Pre-built export payload (tokens.json).
 * @param {{ includePdfs?: boolean }} [options]
 * @returns {Promise<{blob: Blob, bytes: number, fileCount: number, warnings: string[]}>}
 */
export async function buildDeploymentKit(tokens, payload, { includePdfs = true } = {}) {
  /** @type {Record<string, Uint8Array>} */
  const files = {};
  const warnings = [];

  files["DEPLOYMENT.md"] = strToU8(buildGuide(tokens));
  files["tokens.json"] = strToU8(JSON.stringify(payload ?? { tokens }, null, 2));

  for (const token of tokens) {
    const base = `${token.type}-${token.id}`;

    if (token.type === "web-bug") {
      const snippets = buildSnippets(token);
      files[`snippets/${base}.html`] = strToU8(`${snippets.html}\n`);
      files[`snippets/${base}.md`] = strToU8(`${snippets.markdown}\n`);
      files[`snippets/${base}.sh`] = strToU8(`#!/usr/bin/env bash\n${snippets.curl}\n`);
    }

    for (const artifact of token.artifacts ?? []) {
      if (artifact.kind === "file" && artifact.filename) {
        files[`files/${base}/${artifact.filename}`] = strToU8(artifact.value);
      } else if (artifact.kind === "image" && artifact.value) {
        files[`qr/${base}.svg`] = strToU8(artifact.value);
      }
    }

    if (includePdfs && token.type === "pdf") {
      try {
        const { blob, filename } = await generatePdf(token);
        files[`documents/${base}-${filename}`] = new Uint8Array(await blob.arrayBuffer());
      } catch (error) {
        console.warn("[kit] PDF generation failed for token", token.id, error);
        warnings.push(`Could not generate PDF for "${token.label}".`);
      }
    }
  }

  const zipped = zipSync(files, { level: 6 });
  return {
    blob: new Blob([zipped], { type: "application/zip" }),
    bytes: zipped.byteLength,
    fileCount: Object.keys(files).length,
    warnings
  };
}

/** Suggested filename for the archive. */
export function deploymentKitFilename(date = new Date()) {
  return `canary-deployment-kit-${date.toISOString().slice(0, 10)}.zip`;
}
